linters:
  fast: false
  enable-all: true
  disable:
    - gochecknoglobals
    - testpackage
    - err113
    - paralleltest
    - nolintlint
    - cyclop
    - varnamelen
    - ireturn
    - nonamedreturns
    - exhaustruct
    - depguard
    - mnd
    - copyloopvar
    - intrange

    # deprecated
    - exportloopref
